<h1> Assigment 1 </h1>

$D = \{d_{1},\dots, d_{n}\} =>$  Set of documents

$T = \{t_{1},\dots, t_{m}\} =>$ Set of terms (words)

$$TD = (TD_{i,j})_{i =1\dots m,  j=1\dots n}$$

be a matrix such that $TD_{i,j}$ corresponds to the number of times the term $t_{i}$ appears in the document $d_{j}$.

$$L = (l_{1}, \dots, l_{m})$$

let $l_{i}$ be the length, number of characters, of term $t_{i}$.

<h2> Objetices </h2>

* a mathematical expression to calculate it that includes T D, L, constants (scalars, vectors or matrices) and linear algebra operations.


* a expression in [Numpy](http://www.scipy.org) that, when evaluated, generates the requested matrix, vector or scalar (the expression must be a linear algebra expression that does not involve control structures such as for, while etc.)

* the result of evaluating the expression, assuming:

$$ TD = \begin{bmatrix}
    2 & 3 & 0 & 3 & 7 \\
    0 & 5 & 5 & 0 & 3 \\
    5 & 0 & 7 & 3 & 3 \\
    3 & 1 & 0 & 9 & 9 \\
    0 & 0 & 7 & 1 & 3 \\
    6 & 9 & 4 & 6 & 0 \\
\end{bmatrix} L = \begin{bmatrix}
    5 \\
    2 \\
    3 \\
    6\\
    4 \\
    3\\
\end{bmatrix}$$

Finally, assume a process where a document $d_{j}$ is randomly chosen with uniform probability and then a term $t_{i}$, present in $d_{j}$, is randomly chosen with a probability proportional to the frequency of $t_{i}$ in $d_{j}$.

<h2>1. Matrix $P(T, D)$ (each position of the matrix, $P(T, D)_{i,j}$, corresponds to the joint probability of term $t_{i}$ and document $d_{j}$, $P(t_{i}, d_{j}))$</h2>

In [4]:
import numpy as np

TD = np.array([[2,3,0,3,7], [0,5,5,0,3], [5,0,7,3,3], [3,1,0,9,9], [0,0,7,1,3], [6,9,4,6,0]])
L = np.array([[5], [2], [3], [6], [4], [3]])
print(TD)
print(L)

[[2 3 0 3 7]
 [0 5 5 0 3]
 [5 0 7 3 3]
 [3 1 0 9 9]
 [0 0 7 1 3]
 [6 9 4 6 0]]
[[5]
 [2]
 [3]
 [6]
 [4]
 [3]]


In [9]:
P_CONDTD = TD / TD[:, :].sum(axis=0)
print("The conditional probability P(T|D) is equal to:")
print(P_CONDTD)

The conditional probability P(T|D) is equal to:
[[0.125      0.16666667 0.         0.13636364 0.28      ]
 [0.         0.27777778 0.2173913  0.         0.12      ]
 [0.3125     0.         0.30434783 0.13636364 0.12      ]
 [0.1875     0.05555556 0.         0.40909091 0.36      ]
 [0.         0.         0.30434783 0.04545455 0.12      ]
 [0.375      0.5        0.17391304 0.27272727 0.        ]]


In [22]:
P_D = 1. / (np.shape(TD[:, :].sum(axis=0))[0])
P_JOINTD = P_CONDTD * P_D
print("The joint probability P(T|D) is equal to:")
print(P_JOINTD)

The joint probability P(T|D) is equal to:
[[0.025      0.03333333 0.         0.02727273 0.056     ]
 [0.         0.05555556 0.04347826 0.         0.024     ]
 [0.0625     0.         0.06086957 0.02727273 0.024     ]
 [0.0375     0.01111111 0.         0.08181818 0.072     ]
 [0.         0.         0.06086957 0.00909091 0.024     ]
 [0.075      0.1        0.03478261 0.05454545 0.        ]]


<h2>2. Matrix $P(T|D)$</h2>

In [13]:
print("The conditional probability P(T|D) is equal to:")
print(P_CONDTD)

The conditional probability P(T|D) is equal to:
[[0.125      0.16666667 0.         0.13636364 0.28      ]
 [0.         0.27777778 0.2173913  0.         0.12      ]
 [0.3125     0.         0.30434783 0.13636364 0.12      ]
 [0.1875     0.05555556 0.         0.40909091 0.36      ]
 [0.         0.         0.30434783 0.04545455 0.12      ]
 [0.375      0.5        0.17391304 0.27272727 0.        ]]


<h2>3. Matrix $P(D|T)$</h2>

In [19]:
P_T = P_JOINTD[:, :].sum(axis=1)
P_CONDT = P_JOINTD.transpose() / P_T
print("The conditional probability P(D|T) is equal to:")
print(P_CONDT)

The conditional probability P(D|T) is equal to:
[[0.17654612 0.         0.35787437 0.18524987 0.         0.28373832]
 [0.23539482 0.45154704 0.         0.05488885 0.         0.37831776]
 [0.         0.35338464 0.34853851 0.         0.64782097 0.13158879]
 [0.19259576 0.         0.15616336 0.40418153 0.09675248 0.20635514]
 [0.3954633  0.19506832 0.13742376 0.35567975 0.25542655 0.        ]]


<h2>4. Matrix $P(D)$</h2>

In [33]:
print("The probability distribution P(D) is equal to:")
print(np.ones(np.shape(TD[:, :].sum(axis=0))[0]) * P_D)

The probability distribution P(D) is equal to:
[0.2 0.2 0.2 0.2 0.2]


<h2>5. Matrix $P(T)$</h2>

In [31]:
print("The probability distribution P(T) is equal to:")
print(P_T)

The probability distribution P(T) is equal to:
[0.14160606 0.12303382 0.17464229 0.20242929 0.09396047 0.26432806]


<h2>6. $E[l]$ (the expected value of the random variable l corresponding to the length of a randomly chosen term)</h2>

In [35]:
PL = L / np.sum(L)
print("The probability distribution P(L) is equal to:")
print(PL)

The probability distribution P(L) is equal to:
[[0.2173913 ]
 [0.08695652]
 [0.13043478]
 [0.26086957]
 [0.17391304]
 [0.13043478]]


In [37]:
EL = np.sum(PL * L)
print("The expected value of  L is equal to:")
print(EL)

The expected value of  L is equal to:
4.304347826086956


<h2>$Var(l)$ (the variance of $l$)</h2>

In [42]:
E_L2 = np.sum(PL * np.square(L) )

VAR_L = E_L2 - (EL ** 2)
print("The variance of  L is equal to:")
print(VAR_L)

The variance of  L is equal to:
1.7769376181474534
